---
name: yesod-auth-oauth2
version: 0.7.0.0
synopsis: OAuth 2.0 authentication plugins
description: Library to authenticate with OAuth 2.0 for Yesod web applications.
category: Web
author:
  - Tom Streller
  - Patrick Brisbin
  - Freckle Engineering
license: MIT
maintainer: engineering@freckle.com
github: freckle/yesod-auth-oauth2
homepage: http://github.com/freckle/yesod-auth-oauth2

extra-source-files:
  - README.md
  - CHANGELOG.md

ghc-options: -Wall

dependencies:
  - base >=4.9.0.0 && <5

library:
  source-dirs: src
  dependencies:
    - aeson >=0.6
    - bytestring >=0.9.1.4
    - cryptonite >=0.25
    - errors
    - hoauth2 >=1.11.0
    - http-client >=0.4.0
    - http-conduit >=2.0
    - http-types >=0.8
    - memory
    - microlens
    - mtl
    - safe-exceptions
    - text >=0.7
    - uri-bytestring
    - yesod-auth >=1.6.0
    - yesod-core >=1.6.0
    - unliftio

executables:
  yesod-auth-oauth2-example:
    main: Main.hs
    source-dirs: example
    ghc-options:
      - -threaded
      - -rtsopts
      - -with-rtsopts=-N
    dependencies:
      - yesod-auth-oauth2
      - aeson >=0.6
      - aeson-pretty
      - bytestring >=0.9.1.4
      - containers
      - http-conduit >=2.0
      - load-env
      - text >=0.7
      - warp
      - yesod
      - yesod-auth >=1.6.0
    when:
      - condition: ! "!(flag(example))"
        buildable: false

tests:
  test:
    main: Spec.hs
    source-dirs: test
    dependencies:
      - yesod-auth-oauth2
      - hspec
      - uri-bytestring

flags:
  example:
    description: Build the example application
    manual: false
    default: false
