---
name: yesod-auth-oauth2
version: '0.3.1'
synopsis: OAuth 2.0 authentication plugins
description: Library to authenticate with OAuth 2.0 for Yesod web applications.
category: Web
author: Tom Streller
maintainer: Pat Brisbin <pbrisbin@gmail.com>
license: MIT
github: thoughtbot/yesod-auth-oauth2.git
homepage: http://github.com/thoughtbot/yesod-auth-oauth2

ghc-options: -Wall

dependencies:
  - base >=4.9.0.0 && <5

library:
  source-dirs: src
  dependencies:
    - aeson >=0.6 && <1.4
    - bytestring >=0.9.1.4
    - errors
    - hoauth2 >=1.3.0 && <1.6
    - http-client >=0.4.0 && <0.6
    - http-conduit >=2.0 && <3.0
    - http-types >=0.8 && <0.10
    - microlens
    - random
    - safe-exceptions
    - text >=0.7 && <2.0
    - transformers >=0.2.2 && <0.6
    - uri-bytestring
    - yesod-auth >=1.3 && <1.5
    - yesod-core >=1.2 && <1.5

executables:
  yesod-auth-oauth2-example:
    main: Main.hs
    source-dirs: example
    ghc-options:
      - -threaded
      - -rtsopts
      - -with-rtsopts=-N
    dependencies:
      - yesod-auth-oauth2
      - aeson
      - aeson-pretty
      - bytestring
      - containers
      - http-conduit
      - load-env
      - text
      - warp
      - yesod
      - yesod-auth
    when:
      - condition: ! '!(flag(example))'
        buildable: false

tests:
  test:
    main: Spec.hs
    source-dirs: test
    dependencies:
      - yesod-auth-oauth2
      - hspec
      - uri-bytestring

flags:
  example:
    description: Build the example application
    manual: false
    default: false
