---
name: yesod-auth-oauth2
version: '0.3.1'
synopsis: OAuth 2.0 authentication plugins
description: Library to authenticate with OAuth 2.0 for Yesod web applications.
category: Web
author: Tom Streller
maintainer: Pat Brisbin <pat@thoughtbot.com>
license: BSD3
github: thoughtbot/yesod-auth-oauth2.git
homepage: http://github.com/thoughtbot/yesod-auth-oauth2

dependencies:
  - base >=4.8.0.0 && <5

library:
  source-dirs: src
  dependencies:
    - aeson >=0.6 && <1.3
    - bytestring >=0.9.1.4
    - hoauth2 >=1.3.0 && <1.6
    - http-client >=0.4.0 && <0.6
    - http-conduit >=2.0 && <3.0
    - microlens
    - random
    - text >=0.7 && <2.0
    - transformers >=0.2.2 && <0.6
    - uri-bytestring
    - yesod-auth >=1.3 && <1.5
    - yesod-core >=1.2 && <1.5

tests:
  test:
    main: Spec.hs
    source-dirs: test
    dependencies:
      - yesod-auth-oauth2
      - hspec
      - uri-bytestring
