---
resolver: lts-12.2
extra-deps:
  - hoauth2-1.7.2
  - uri-bytestring-aeson-0.1.0.6
ghc-options:
  "$locals": -fhide-source-paths

# needed so resourcet can get exceptions-0.10 even though hoauth dislikes it
allow-newer: true
