name: CI

on:
  pull_request:
  push:
    branches: main

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  test:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        stack-yaml:
          - stack-nightly.yaml     # ghc-9.4 + hoauth2-2.8.0
          - stack.yaml             # ghc-9.2
          - stack-lts-19.33.yaml   # ghc-9.0
          - stack-lts-18.28.yaml   # ghc-8.10
          - stack-lts-16.31.yaml   # ghc-8.8
          - stack-lts-14.27.yaml   # ghc-8.6 + hoauth2-1.14.0
          - stack-hoauth2-2.6.yaml # ghc-9.4 (nightly-2022-12-09)
          - stack-hoauth2-2.3.yaml # ghc-9.0 (nightly-2022-02-25)
          - stack-hoauth2-2.2.yaml # ghc-9.0 (nightly-2022-02-25)
          - stack-hoauth2-2.0.yaml # ghc-8.10
      fail-fast: false

    steps:
      - uses: actions/checkout@v3
      - uses: freckle/stack-action@v4
        with:
          stack-yaml: ${{ matrix.stack-yaml }}
          stack-arguments: --flag yesod-auth-oauth2:example

  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: haskell/actions/hlint-setup@v2
      - uses: haskell/actions/hlint-run@v2
        with:
          fail-on: warning
