name: CI

on:
  pull_request:
  push:
    branches: main

jobs:
  test:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        stack-yaml:
          - stack-nightly.yaml
          - stack.yaml
          - stack-lts-17.4.yaml
          - stack-lts-16.10.yaml
          - stack-lts-13.2.yaml
          - stack-hoauth2-2.0.yaml
          - stack-hoauth2-2.2.yaml
          - stack-hoauth2-2.3.yaml
          - stack-hoauth2-2.6.yaml
      fail-fast: false

    steps:
      - uses: actions/checkout@v3
      - uses: freckle/stack-cache-action@v2
        with:
          stack-yaml: ${{ matrix.stack-yaml }}
      - uses: freckle/stack-action@v3
        with:
          stack-yaml: ${{ matrix.stack-yaml }}
          stack-arguments: --flag yesod-auth-oauth2:example

  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run:
          curl --output .hlint.yaml https://raw.githubusercontent.com/pbrisbin/dotfiles/master/hlint.yaml
      - uses: rwe/actions-hlint-setup@v1
      - uses: rwe/actions-hlint-run@v2
        with:
          fail-on: warning
